import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { MantineProvider } from "@mantine/core";
import AppHeader from "./main/layouts/AppHeader/AppHeader";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "La.vid | Make your skin more vibrant, La.vid | Skincare brand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MantineProvider defaultColorScheme="light">
          <AppHeader />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
